---
version: '3'
services:
  website:
    container_name: website
    restart: unless-stopped
    build: .
    networks:
      - services
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=services"
      - "traefik.web.port=80"
      - "traefik.web.entryPoints=https"
      - "traefik.web.frontend.rule=Host:opinma.de,www.opinma.de"

networks:
  services:
    external: true
